// client/src/Components/LoginBadge.vue
<template>
    <div class="buttons" v-if="!name">
      <a class="button is-primary">
            <strong>Sign up</strong>
        </a>
        <a class="button is-light" @click="login">Log in
        </a>
    </div>
    <div v-else>
        Hello {{name}}
    </div>
</template>

<script>
import Session, {Login} from "../services/session";

export default {
    data: ()=>({
        Session
    }),
    methods:{
        login(){
            console.log(Session);
            Login();
            console.log(Session);
        }
    },
    computed:{
        name(){
            return this.Session.user.Firstname + ' ' + this.Session.user.Lastname
        }
    }
}
</script>

<style>

</style>

// react-app/src/components/LoginBadge.js
import Session from "../services/session";
    function login(params) {
              this.$router.push('/login');
    }
    function name(params) {
                    return this.Session.user.firstName + ' ' + this.Session.user.lastName;

    }

export default () => !Session.user ?;

<div class="buttons">
    <a className="button is-primary">
        <strong>Sign-up</strong>
    </a>
    <a className="button is-light" click="login">Loging</a>
</div>:
<div>
    hello {{name}}
</div>
